# Generated by Django 5.2.15 on 2026-07-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="cloudflare_meeting_id",
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="farmer_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="vet_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
