# Generated by Django 5.2.15 on 2026-08-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meeting_cloudflare_meeting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerrequest',
            name='source',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('PORTAL', 'Portal')], default='PORTAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmerrequest',
            name='problem',
            field=models.CharField(max_length=555),
        ),
    ]
