# Generated by Django 5.2.15 on 2026-08-24 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_farmerrequest_source_alter_farmerrequest_problem"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "farmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("CATTLE", "Cattle"),
                            ("POULTRY", "Poultry"),
                            ("GOAT", "Goat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("farmer", "animal_type"),
                        name="unique_farmer_animal_type",
                    )
                ],
            },
        ),
    ]
