# Generated by Django 5.2.15 on 2026-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rewardaccount_livestock"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerrequest",
            name="age",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="animal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOG", "Dog"),
                    ("CAT", "Cat"),
                    ("COW", "Cow"),
                    ("GOAT", "Goat"),
                    ("BUFFALO", "Buffalo"),
                    ("SHEEP", "Sheep"),
                    ("POULTRY", "Poultry"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="breed",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="health_problem",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="link_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="farmerrequest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="farmerrequest",
            name="problem",
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
