# Generated by Django 5.2.15 on 2026-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_farmerrequest_age_farmerrequest_animal_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerrequest",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="farmer_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmerrequest",
            name="vet_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="farmerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ASSIGNED", "Assigned"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("MEETING_CREATED", "Meeting Created"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vet",
            name="speciality",
            field=models.CharField(default="General Veterinary", max_length=255),
        ),
    ]
