# Generated by Django 5.2.15 on 2026-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_farmerrequest_expires_at_farmerrequest_farmer_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerrequest",
            name="animal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOG", "Dog"),
                    ("CAT", "Cat"),
                    ("COW", "Cow"),
                    ("GOAT", "Goat"),
                    ("BUFFALO", "Buffalo"),
                    ("SHEEP", "Sheep"),
                    ("POULTRY", "Poultry"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
