# Generated by Django 5.2.15 on 2026-09-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="vet",
            name="cgpa",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="vet",
            name="license_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="vet",
            name="nid",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="vet",
            name="university",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
