from django.urls import path
from .views import (
    health_check,
    create_meeting,
    CustomLoginView,
    FarmerSignupView,
    CreateFarmerRequestView,
    FarmerDashboardView,
    FarmerProfileView,
    FarmerRequestsListView,
    VetAssignedRequestsView,
    VetDashboardView,
    VetProfileView,
    VetAssignedMeetingsView,
    VetResponseView,
    CompleteConsultationView,
    CompleteConsultationByParticipantView,
    logout_view,
    MeetingDetailByUUIDView,
    guest_request_create,
    guest_request_status,
    CreateConsultationRequestView,
    ConsultationStatusView,
    FarmerJoinMeetingView,
)

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('meeting/create/', create_meeting, name='create_meeting'),
    path('auth/login/', CustomLoginView.as_view(), name='api_login'),
    path('auth/signup/', FarmerSignupView.as_view(), name='api_signup'),
    path('auth/register/', FarmerSignupView.as_view(), name='api_register'),  # Alias for signup
    path('auth/logout/', logout_view, name='api_logout'),
    path('farmer/request/create/', CreateFarmerRequestView.as_view(), name='farmer_request_create'),
    path('farmer/request/list/', FarmerRequestsListView.as_view(), name='farmer_request_list'),
    path('farmer/dashboard/', FarmerDashboardView.as_view(), name='farmer_dashboard'),
    path('farmer/profile/', FarmerProfileView.as_view(), name='farmer_profile'),
    path('farmer/consultation/create/', CreateConsultationRequestView.as_view(), name='consultation_create'),
    path('farmer/consultation/<str:request_id>/status/', ConsultationStatusView.as_view(), name='consultation_status'),
    path('consultations/<str:request_id>/complete/', CompleteConsultationByParticipantView.as_view(), name='consultation_complete'),
    path('consultations/<str:request_id>/join/', FarmerJoinMeetingView.as_view(), name='consultation_join'),
    path('vet/dashboard/', VetDashboardView.as_view(), name='vet_dashboard'),
    path('vet/profile/', VetProfileView.as_view(), name='vet_profile'),
    path('vet/request/list/', VetAssignedRequestsView.as_view(), name='vet_request_list'),
    path('vet/meetings/', VetAssignedMeetingsView.as_view(), name='vet_meetings'),
    path('vet/requests/<str:request_id>/respond/', VetResponseView.as_view(), name='vet_respond'),
    path('vet/requests/<str:request_id>/complete/', CompleteConsultationView.as_view(), name='vet_complete'),
    path('internal/meeting/<uuid:meeting_uuid>/', MeetingDetailByUUIDView.as_view(), name='meeting_detail_uuid'),
    path('guest/request/', guest_request_create, name='guest_request_create'),
    path('guest/request/<str:request_id>/', guest_request_status, name='guest_request_status'),
]